version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-wheelzhub
    environment:
      MYSQL_ROOT_PASSWORD: wheelzhub
      MYSQL_DATABASE: wheelzhub
      MYSQL_USER: wheelzhub
      MYSQL_PASSWORD: wheelzhub
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
